name: 'Repository Contributors Chart Generator'
description: 'Generate a HTML chart of the contributors and place it in the README'
author: 'Salgado2004'
runs:
  using: 'node20'
  main: 'dist/index.js'
