name: 'Contributors README Chart Generator'
description: 'Generate a HTML chart of the contributors and place it in the README'
author: 'Salgado2004'
branding:
  icon: 'users'
  color: 'blue'
inputs:
  token:
    description: 'Repository secret token'
    required: true
  contributions:
    description: 'Contributions scope'
    required: false
    default: 'repo'
  include-bots:
    description: 'Boolean flag to include bot contributors'
    required: false
    default: true
  path:
    description: 'The alternate path to look for a README file'
    required: false
  limit:
    description: 'Max number of contributors you want to display in the chart'
    required: false
    default: 24
runs:
  using: 'node20'
  main: 'dist/index.js'
